### ISSUE TITLE
MoU12 m4 complete "System improvements"

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#19]
Assisting AARNet with some user acceptance testing when updating
including an investigation into http/2 testing and how it may help or
possibly hinder download functionality and performance.

Discussion and investigation about streaming crypto (StreamSaver) with
Rick van Rein in July to assure functionality is as expected. One
outcome is PR 1070 cited below.

missing end of function added after acceptance of pr 987
https://github.com/filesender/filesender/pull/989

review and merge of Chunked storage, crypto UX improvements
https://github.com/filesender/filesender/pull/990

release 2.24
https://github.com/filesender/filesender/pull/993

review and merge to menu and favicons update for bootstrap
https://github.com/filesender/filesender/pull/994

review and merge of 4 new build options for docker
https://github.com/filesender/filesender/pull/995

review and merge of Update build badge
https://github.com/filesender/filesender/pull/996

Update to user_can_only_view_guest_transfers_shared_with_them for wider scope
https://github.com/filesender/filesender/pull/1001

New languages added to auto import script
https://github.com/filesender/filesender/pull/1010
https://github.com/filesender/filesender/pull/1080
https://github.com/filesender/filesender/pull/1081
https://github.com/filesender/filesender/pull/1082
https://github.com/filesender/filesender/pull/1083

i18n related
https://github.com/filesender/filesender/pull/1034
https://github.com/filesender/filesender/pull/1046
https://github.com/filesender/filesender/pull/1079

review and merge of Cast anonymous recipient identity to string
https://github.com/filesender/filesender/pull/1012

review and merge of
https://github.com/filesender/filesender/pull/1014
https://github.com/filesender/filesender/pull/1014

review and merge of dep update for docs
https://github.com/filesender/filesender/pull/1015
https://github.com/filesender/filesender/pull/1042

ui: feedback for bad characters in file names during adding
https://github.com/filesender/filesender/pull/1033
https://github.com/filesender/filesender/pull/1035
https://github.com/filesender/filesender/pull/1036

review and merge of Add documentation for 7 config options
https://github.com/filesender/filesender/pull/1037

deps: bump versions using scripts/dev/www-lib-update
https://github.com/filesender/filesender/pull/1039

comments: zip64 handler call the sig a magic number instead
https://github.com/filesender/filesender/pull/1041

release 2.25
https://github.com/filesender/filesender/pull/1047

review and merge of fix documentation section about auth_remote_applications 
config ref #1040
https://github.com/filesender/filesender/pull/1048

update for docs
https://github.com/filesender/filesender/pull/1053
https://github.com/filesender/filesender/pull/1068
https://github.com/filesender/filesender/pull/1109

This vacates the default URL for mitm in StreamSaver
https://github.com/filesender/filesender/pull/1070

Some PBKDF2 dialog updates
https://github.com/filesender/filesender/pull/1072
https://github.com/filesender/filesender/pull/1073

review and merge of only show green graph when encryption_mandatory set
https://github.com/filesender/filesender/pull/1074

review and merge of fix Chunked storage free space check, while not breaking 
standard class
https://github.com/filesender/filesender/pull/1075

show download progress as simple percentage again
https://github.com/filesender/filesender/pull/1077

upload page and encryption password messages
https://github.com/filesender/filesender/pull/1090
https://github.com/filesender/filesender/pull/1103
https://github.com/filesender/filesender/pull/1105

improvements to help S3 storage
https://github.com/filesender/filesender/pull/1091
https://github.com/filesender/filesender/pull/1108

bring back about and help page text
https://github.com/filesender/filesender/pull/1095

release 2.27
https://github.com/filesender/filesender/pull/1096

review and update to add a lock near transfer id for encrypted transfers 
https://github.com/filesender/filesender/pull/1101

review and merge of enable fill on graphs (lost/new setting when updated 
chart.js)
https://github.com/filesender/filesender/pull/1115

discussion about some language translations perhaps not being what
we might like

translate_email xss and mimetype attacks reported by SURFnet
https://github.com/filesender/filesender/pull/1121

discussions on IPR

Some documentation and testing with PDO::ATTR_PERSISTENT for
persistent database connections and postgresql leading to improved
documentation.
https://github.com/filesender/filesender/pull/1119

Release 2.29 and matching release 3.0alpha1 including some additional
integration testing and updates after merging 2.29 functionality into
3.0x series.
https://github.com/filesender/filesender/pull/1122
https://github.com/filesender/filesender/releases/tag/master3-filesender-3.0alpha1

Upload page graph presentation improvements after updating chartjs
to allow the site to work with CSP inline with security audit (pr 1089).
https://github.com/filesender/filesender/pull/1124

Ability to disable the guest system if desired including
some code to explicitly reject attempts to access it on a disabled system.
https://github.com/filesender/filesender/pull/1125

A new option to allow download of files only from authenticated users
https://github.com/filesender/filesender/pull/1126

Count every download regardless of if it comes from the same ipv4 address
https://github.com/filesender/filesender/pull/1127

Service level AUP with basic versioning
https://github.com/filesender/filesender/pull/1128

A new secondary index on transfers.expires to help cron execution times
https://github.com/filesender/filesender/pull/1129

Some more of the configuration directives now have documentation
https://github.com/filesender/filesender/pull/1130

Translation import
https://github.com/filesender/filesender/pull/1131

3.x series: The buttons on the download page for each file are now
"primary" buttons to indicate that they are the main items to see on
the page.
https://github.com/filesender/filesender/pull/1133

Release 3.30 with matching 3.0alpha2
https://github.com/filesender/filesender/pull/1132
https://github.com/filesender/filesender/pull/1135
https://github.com/filesender/filesender/releases/tag/master3-filesender-3.0alpha2

**Comment by meijer** [comment]
Recommended to board for acceptance.

**Comment by meijer** [comment]
The board voted, and unanymously accepted delivery of MoU12 Milestone 4. 

A request to NLnet to pay Dr. Martin from the FileSender earmarked fund has been sent.

**Comment by monkeyiq** [comment]
ok this is completed now.
