### ISSUE TITLE
Possible integration of two docs sites into a single repository?

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#21]
The docs.filesender.org site is currently generated from two github repositories. The landing page comes from
https://github.com/filesender/filesender.github.io
which makes the default
http://docs.filesender.org

The pages under that site are generated from the below site with their own index page:
https://github.com/filesender/filesender/blob/development/docs/index.md

That site is written to http://docs.filesender.org/filesender/

The links in the former filesender.github.io are to for example, 
https://docs.filesender.org/v2.0/
instead of 
https://docs.filesender.org/filesender/v2.0/

Since filesender.github.io is only a single page I am wondering if we should merge that index and the index from https://github.com/filesender/filesender/blob/development/docs/index.md and make a single source for the entire site at `docs.filesender.org` 

The other option is to update the links from filesender.github.io to include the /filesender/ prefix so they work again which I might do as a first measure so things work again while we decide if a merge is desired.

**Comment by monkeyiq** [comment]
I have updated the links from the docs.filesender.org site to point at the site generated from docs 
https://github.com/filesender/filesender.github.io/pull/2

**Comment by WebSpider** [comment]
The reason for https://docs.filesender.org/filesender/ serving the content of https://github.com/filesender/filesender/blob/development/docs/index.md is documented here: 

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#supported-custom-domains

"if the custom domain for your user site is www.octocat.com, and you have a project site with no custom domain configured that is published from a repository called octo-project, the GitHub Pages site for that repository will be available at www.octocat.com/octo-project."

As far as I am concerned, current situation may be a bit strange with one repository only serving as index, but changing this to make the main filesender repository serve everything also has its own drawbacks, so with the change done in nov 2021, this situation is "good enough"

**Comment by meijer** [comment]
If Ben also agrees with Nils conclusion I close the ticket. Bit of background - reason why we went with github.io is to have a (as it turns out very) stable place to serve FileSender documentation from and this bit with the two repositories was iirc just the way it needed to work at the time.
