### ISSUE TITLE
MoU13 m2b complete "Selenium Continuous Integration test update (part b)"

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#23]
The test cases in LanguageSelectTest.php, HeaderMenuTest.php, MaxFilesTest.php, InvalidExtensionsTest.php, MaxUploadSizeTest.php, and TemplatingTest.php have been updated to work against the development3 branch and the bootstrap UI refresh.

This was introduced in https://github.com/filesender/filesender/pull/1185.

An issue that was addressed post 1185 was the language selection on smaller displays and the new wait...() methods.
https://github.com/filesenderuici/filesender/runs/4746227552?check_suite_focus=true

The first sucessful run of the new tests
https://github.com/filesenderuici/filesender/runs/4746557771?check_suite_focus=true

One of the complicated interactions is updating the server configuration from a unit test. This can introduce complicated caching issues where the browser does not see the very latest data and so can introduce wait and force reload requirements.

With this milestone in place the UI test suite running against development3 will be the same or better than that running against the current FileSender 2.x releases.

**Comment by monkeyiq** [comment]
Both m2a and m2b tests are now enabled https://github.com/filesender/filesender/pull/1195

**Comment by meijer** [comment]
Milestone as defined in MoU:

_"FileSender includes 10 unit tests which use Selenium to control a web browser to verify expected functionality and expected failure of the system. The Selenium tests are run with Sauce Labs to verify that proposed updates in pull requests do not break system functionality.
This milestone will update the listed tests to function on the FileSender 3.x alpha (using Bootstrap for UI). In addition to updating to cater for the user interface the Selenium tests should be refreshed to use busy waits where possible. Currently the test system contains many race conditions which are only resolved by explicitly waiting longer than needed before continuing. It is proposed to instead inspect the web page for elements and visibility and/or use javascript to determine explicitly if the web browser is presenting an expected state.

Deliverable:
• A release with the LanguageSelectTest.php, HeaderMenuTest.php, MaxFilesTest.php, InvalidExtensionsTest.php, MaxUploadSizeTest.php, TemplatingTest.php test cases updated as described."_

Milestone delivery checked, acceptance recommended to the board and called for vote.

**Comment by meijer** [comment]
Board accepted. Request for payment sent to NLnet

**Comment by monkeyiq** [comment]
Payment received, thank you.
