### ISSUE TITLE
MoU13 m1 complete "System improvements"

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#24]
System maintenance tasks performed in the period September 7, 2021 to January 22, 2022.

Code was ported forward from the 2.x series to create 3.0 alpha release 3.

Review + Merge: Added in the list: Cyprus | Frederick University 
https://github.com/filesender/filesender/pull/1142

update key_version_kew_files docs
https://github.com/filesender/filesender/pull/1144

build(deps): bump nokogiri from 1.11.7 to 1.12.5 in /docs
https://github.com/filesender/filesender/pull/1147

ui: check that msg does not contain password on password entry too
https://github.com/filesender/filesender/pull/1152

Review + Merge: Fixed bug of python script (filesize multiple of chunk size)
https://github.com/filesender/filesender/pull/1153
https://github.com/filesender/filesender/pull/1155

docs: add contributing info
https://github.com/filesender/filesender/pull/1154

docs: update with more information about 3.x series
https://github.com/filesender/filesender/pull/1170

Review + Update: clouds3: option to store everything in a single bucket
https://github.com/filesender/filesender/pull/1175

update metadata that is shared in filesender-config.js.php
https://github.com/filesender/filesender/pull/1176

some docs for crypto_crypt_name and update to fully set crypto_crypt_name from key version
https://github.com/filesender/filesender/pull/1177

upload: show a very basic ETA
https://github.com/filesender/filesender/pull/1178

ui: prevent upload page expires from becoming an empty string
https://github.com/filesender/filesender/pull/1179

Review + Merge: Fixes to allow running under PHP8
https://github.com/filesender/filesender/pull/1180

Review + Merge: Patch 1 [ed: setup scripts update]
https://github.com/filesender/filesender/pull/1181

Review + Merge: url-encode email address in admin_transfers
https://github.com/filesender/filesender/pull/1196

guest expires: allow selection below the default expire
https://github.com/filesender/filesender/pull/1207

Review + Update: New Env class to allow getenv() to do more in some cases
https://github.com/filesender/filesender/pull/1208
https://github.com/filesender/filesender/pull/1209

New optional use of the Notification API to indicate upload complete
https://github.com/filesender/filesender/pull/1210

Halt of Savage CI server while Log4j vulnerability was investigated.
Keys changed at this time as good security practice.

**Comment by meijer** [comment]
Milestone as defined in MoU:

FileSender needs to run maintenance free and handle tens of thousands of users on a single install without problems. This task makes several improvements to the software to improve overall performance, stability and security. Currently there are two branches that represent the released 2.x series and the upcoming 3.x series which also need to be kept up to date with each other.

Milestone delivery checked, acceptance recommended to the board and called for vote.

It's a nice list of fixes, small community-requested improvements and responding to security issues. I want to say on behalf of the board that we also really appreciate your responsiveness to the user community on the -dev list. Your efforts in this respect have significantly improved community dynamics over the past years, and it shows when you're tracking the mailing list from a distance. Case in point, the recent compliment from rizlas with the PR fixing the Italian language file.

**Comment by meijer** [comment]
Board accepted. Request for payment sent to NLnet

**Comment by monkeyiq** [comment]
Payment received, thank you.
