### ISSUE TITLE
Decide how to progress with the Bootstrap UI effort after initial MoU11 work completed

### ISSUE THREAD

**Issue by meijer** [filesender/governance#3]
Lead dev Ben Martin reports:

"I have asked the FileSender board how they wish to progress with this. I 
floated the options (a) through (d) mentioned below. The version 2.25 could be 
a later point release, it is just used for a placeholder. 

a) Switch to bootstrap with a minor point release. For example 2.25 introduces 
the bootstrap UI and we just deprecate the old UI.

b) Run a few releases in parallel. So 2.25 is release both using the old UI 
and also a bootstrap release with the new UI is made as well. Sites are 
encouraged to use the bootstrap UI if possible but can fall back to the same 
functionality and security updates if something doesn't currently meet their 
needs. This might be done for 2-3 point releases or longer if desired.

c) A series of prereleases to FileSender 3 which uses the bootstrap UI.

d) Something the board [or community] wants but wasn't mentioned above."

**Comment by WebSpider** [comment]
The switch to a new UI framework could quite-possibly break the template overrides (from functioning, and as such should be considered backwards incompatible. If people upgrade their install from 2.x to 2.x+1 the expectation is that things continue to work as they do now.

Also, the filesender v1 codebase is effectively unmaintained, and should therefore no longer be considered deprecated (https://github.com/filesender/filesender/blob/development/docs/index.md#which-version-should-you-choose), but totally unsupported.

For William and me this calls for a new major release (filesender 3.0(.0?)), to handle the following:

- Getting the new bootstrap UI functionally equivalent in a set of prereleases and release candidates
- Drafting up a support statemement (maybe something for a card on https://github.com/filesender/governance/projects/1) for releases, of which the following 2 bullets are a suggestion:
- Formal goodbye to filesender v1. Once filesender v3 is released, we mark it unsupported. Cleanup of the git branches related to it, leaving only release tags. Cleanup of the documentation in the master branch referring to filesender v1 as well. No cleanup of commits or svn imports, as these are part of project (development) history
- Deprecation of filesender v2. From filesender v3 release until a moment to be chosen in the future only security updates will be applied to v2, after which it will become unsupported. Code will no longer be audited. This time, let's not choose 6 years (filesender 1.6 was released 30/12/2015)

So we choose option C.

**Comment by madsi1m** [comment]
@WebSpider it defiantly does break templates (but in a good way)
I think a few versions of current UI with "test versions" of new UI in parallel and have v3 as just the new UI. Gives people time to test/get ready for v3

**Comment by WebSpider** [comment]
@madsi1m Yeah, that's basically what I'm proposing too, but just naming them v3-prereleases, so it's clear where it's headed

**Comment by meijer** [comment]
So here's the current view of the board. 

The community is responding positively on the bootstrap effort, both before, during and after the BoF this month. There are several community stakeholders with active deployments keen to deploy (and thus field-test at scale) the new UI. So all in all, the Bootstrap UI appears the way to go. 

The new UI breaks backwards compability hence naming it 'v3' seems appropriate, taking into account the recent discussion on using SemVer. 

We have few resources in the development effort, and actively developing two branches for production use is an extra effor we could do without.  Ben: please correct me if we're judging the impact of two branches to be larger than it is. We've also observed earlier that the most effective way to test large scale deployment is actually in the field. 

Ben reports that te Bootstrap UI code is in good shape, but obviously hasn't been large-scale field tested yet, so there might be cases that haven't been tested. 

So the gist of what we'd like to do:
- progress a version 3 with the new Bootstrap UI _and concentrate our effort on this_. This probably requires a couple of pre-releases that someone needs to be willing to put out in a large-scale field-test
- freeze 2.x development on the last 2.x release, and only do security fixes and possibly fixes of serious bugs, noting that we haven't had those for a while
- do other new functionality development on the 3.x line

And following on what WebSpider commented: 
- a formal goodbye to FileSender v1.x
- a support policy (we used to have one but that's several years ago)
- decide on supported life time for FileSender 2.x. We should probably ask for some community input, but 6 years is indeed too long ;)

-

**Comment by jornane** [comment]
> The new UI breaks backwards compability hence naming it 'v3' seems appropriate, taking into account the recent discussion on using SemVer.

I agree with this, option c) seems to be the preferred one.

> progress a version 3 with the new Bootstrap UI _and concentrate our effort on this_. This probably requires a couple of pre-releases that someone needs to be willing to put out in a large-scale field-test

It would be useful to designate the branch as "this is going to be FileSender 3", so us early adopters can keep following that branch and eventually "slide into" running FileSender 3 in production.

> decide on supported life time for FileSender 2.x. We should probably ask for some community input, but 6 years is indeed too long ;)

Uninett has been running an old version of FileSender for a very long time, and we are not aware of any security problems with it. If FileSender still has the good track record that it had back then, supporting it doesn't take a lot of time. Then again, you might not know that before you make the guarantee, so I agree that the period should not be too long.

> a support policy (we used to have one but that's several years ago)

I would really like a "we don't do database schema changes within a patch release", so FileSender x.0.y has ONE schema, if the database schema has to change you call it FileSender x.1.0 or FileSender (x+1).0.0, and you keep supporting FileSender x.0 for a while.  This makes for easier, and more stable upgrades.

**Comment by WebSpider** [comment]
> > progress a version 3 with the new Bootstrap UI _and concentrate our effort on this_. This probably requires a couple of pre-releases that someone needs to be willing to put out in a large-scale field-test
> 
> It would be useful to designate the branch as "this is going to be FileSender 3", so us early adopters can keep following that branch and eventually "slide into" running FileSender 3 in production.
>
 
I think that would naturally be the active development branch :-)

> > a support policy (we used to have one but that's several years ago)
> 
> I would really like a "we don't do database schema changes within a patch release", so FileSender x.0.y has ONE schema, if the database schema has to change you call it FileSender x.1.0 or FileSender (x+1).0.0, and you keep supporting FileSender x.0 for a while. This makes for easier, and more stable upgrades.

Yeah, I agree on this one. When using semver-alike methods, its usually something like:

MAJOR.MINOR.PATCH-PRE
MAJOR release is needed if you break backward compatibility
MINOR release is needed if you add functionality in a backward compatible manner
PATCH is needed if you make backward compatible (bug)fixes, documentation updates, etc
PRE can be used to indicate a prerelease version, which would typically have alfa,beta,release candidates for a new major or minor release. 

Using this scheme, a database update would be accompanied by a backward compatible feature update usually, so this would be a new minor release. But this needs further hashing out in the policies project (https://github.com/filesender/governance/projects/1)

**Comment by jornane** [comment]
> > > progress a version 3 with the new Bootstrap UI _and concentrate our effort on this_. This probably requires a couple of pre-releases that someone needs to be willing to put out in a large-scale field-test
> > 
> > 
> > It would be useful to designate the branch as "this is going to be FileSender 3", so us early adopters can keep following that branch and eventually "slide into" running FileSender 3 in production.
> 
> I think that would naturally be the active development branch :-)

Does that mean that the development branch will get the bootstrap UI merged immediately? Then that's a very good solution.

> > I would really like a "we don't do database schema changes within a patch release", so FileSender x.0.y has ONE schema, if the database schema has to change you call it FileSender x.1.0 or FileSender (x+1).0.0, and you keep supporting FileSender x.0 for a while. This makes for easier, and more stable upgrades.
> 
> Yeah, I agree on this one. When using semver-alike methods, its usually something like:
> 
> MAJOR.MINOR.PATCH-PRE
> MAJOR release is needed if you break backward compatibility
> MINOR release is needed if you add functionality in a backward compatible manner
> PATCH is needed if you make backward compatible (bug)fixes, documentation updates, etc
> PRE can be used to indicate a prerelease version, which would typically have alfa,beta,release candidates for a new major or minor release.

I think we're saying the same thing? If newest is FileSender x.0.42 and a database change comes up, the resulting version is x.1.0, not x.0.43. Another way of putting it is that patch versions will never have database schema changes.

**Comment by zivel** [comment]
Hello Filesender people

We at SWITCH need to finally move from our ancient 1.something installation ([although already pimped with Bootstrap 3](https://filesender.switch.ch/)) to a more current one. 

Should we just use the bootstrap branch or will there be a Release Candidate of Filesender 3 in the next few days? If the version we use works fine, we will put that into production, so we can be that large-scale field-test that some were mentioning here. Of course as Switzerland isn't that large it's not the largest-scale but we do have [around 2.5k users a month](https://cloud-id.switch.ch/filesender/).

Oh and what we have seen so far from then new bootstrapped Filesender, we like! Thank you for the great work :)
- Renato

**Comment by meijer** [comment]
The consensus seems to be for:
- bootstrap development branch becomes new default development branch and
will be numbered 3.x 
- the current development (2.x) branch no longer
receives new features, but does receive security and bug fixes where
appropriate for some time, until 3.x has matured to a certain level
(“certain level” to be specified, so that we don’t incur a too long term
support load)

This means no active development on 2 branches but on 1, and all active
development effort goes in to the ‘bootstrap’ branch.

**The board supports the above approach.**

Ben suggested he'd rename development to development 2, and then the current boutstrap branch would become just development. 

With that, this issue can be closed.
