### ISSUE TITLE
MoU14 m1 complete: System improvements

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#30]
System maintenance tasks performed in the period 23 January to 28 July 2022.

This includes time spent investigating the TCP_WAIT stalling issue that was reported on the mailing list and the TeraSender web workers issue that can effect some network confugrations https://github.com/filesender/filesender/issues/1226. Unfortunately no decisive result has been found for either issue as yet.

Updates included in this milestone include:

Update to versions of javascript dependencies https://github.com/filesender/filesender/pull/1239 https://github.com/filesender/filesender/pull/1202

Bulk import of language translations from poeditor performed https://github.com/filesender/filesender/pull/1243 https://github.com/filesender/filesender/pull/1242

update for use_strict_csp=true configurations https://github.com/filesender/filesender/pull/1247

Update docker images to newest releases https://github.com/filesender/filesender/pull/1270

Update for service AUP translation string https://github.com/filesender/filesender/pull/1280

GUI allowed pages update to move these settings to the config https://github.com/filesender/filesender/pull/1282

documentation fixes https://github.com/filesender/filesender/pull/1262
Adding documentation for 9 options https://github.com/filesender/filesender/pull/1269
Update known-installs.md https://github.com/filesender/filesender/pull/1263

update oldterms.txt https://github.com/filesender/filesender/pull/1281

### dev3
 update popper.js handling code and version https://github.com/filesender/filesender/pull/1252
 update bootstrap and bootbox metadata https://github.com/filesender/filesender/pull/1253
 remove reset.css and cleanup border on transfers pager https://github.com/filesender/filesender/pull/1254
 update from deprecated flag-icon-css to newer flag-icons https://github.com/filesender/filesender/pull/1255

### deps
  update composer.lock for optional dep directory https://github.com/filesender/filesender/pull/1250
  bump guzzlehttp/guzzle 7.4.5 https://github.com/filesender/filesender/pull/1257 https://github.com/filesender/filesender/pull/1258  https://github.com/filesender/filesender/pull/1265 https://github.com/filesender/filesender/pull/1266 https://github.com/filesender/filesender/pull/1271 https://github.com/filesender/filesender/pull/1272 https://github.com/filesender/filesender/pull/1274

### developers
  a new dump method for debugging https://github.com/filesender/filesender/pull/1256

This update changes some database numeric keys to larger types. It is recommended to make a database backup before running the database.php script. These keys have expanded in size in all database backends to avoid potential overflow issues.

For mysql/mariadb databases only, the size of meduimint has also changed from 24 to 32 bit. Some uses of mediumint have foreign keys so can not be directly updated. To help with this a new script `scripts/upgrade/migration-drop-foreign-keys.php` was created. The database.php script will ensure that foreign keys are created if they do not exist so explicitly dropping them before running database.php should be ok. 

For this release, if you are using mysql or mariadb you will need to run the following to update the database. If there is a permission issue with the migration-drop-foreign-keys.php script the SQL commands are contained in the script and can be run directly from the mysql console.
```
cd scripts/upgrade
php migration-drop-foreign-keys.php
php database.php
```

If you are running PostgreSQL then expanding the size of the keys for files, guests etc should change with just the normal command:
```
php database.php
```

### Database

convert files, filecollections, guests and transfer ids to bigints https://github.com/filesender/filesender/pull/1294 https://github.com/filesender/filesender/pull/1296
Only mysql/mariadb moved meduimint from 24 to 32 bit https://github.com/filesender/filesender/pull/1295

### General

Only send a single email with all downloaded files listed after encrypted download to zip https://github.com/filesender/filesender/pull/1286

A new test for the character set encoding for mysql/mariadb with a warning and override if utf8mb4 is not in use https://github.com/filesender/filesender/pull/1287

A new script to gather system information for issue reports https://github.com/filesender/filesender/pull/1288

An update to upload page to convert blank expire time to original value. This appeared to happen before but the stored expire time was not correct. https://github.com/filesender/filesender/pull/1289

i18n: import script update to better respect the context of a translation https://github.com/filesender/filesender/pull/1291
i18n: auto import from poedtor on 2022-07-14-1657781263 https://github.com/filesender/filesender/pull/1290

build(deps): bump tzinfo from 1.2.9 to 1.2.10 in /docs https://github.com/filesender/filesender/pull/1298

**Comment by meijer** [comment]
Ben, did we (the board) accept this milestone?

**Comment by monkeyiq** [comment]
I think it is still pending board acceptance.

**Comment by meijer** [comment]
Let the record show that the board _did_ accept this milestone (!)
