### ISSUE TITLE
Is IE11 still supported in FileSender

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#5]
Do we wish to continue to try to support IE11 or should be retire that now and focus only on modern browsers?

**Comment by meijer** [comment]
The feedback from the BoF on 1 March 2021 indicates that the community supports dropping IE11 support for future versions of FileSender. Microsoft itself will drop IE11 support for it's Office 365 product suite per August 2021. Many others already discontinued support. 

To keep supporting IE11 very likely means we'll have to do investments especially to keep things working in IE11. That'll slow down feature development/feature improvement, it'll hinder us to take advantage of modern browser features, and it'll be in general a drain on scarce resources.

All things considered the board intends to decide to NOT invest further in supporting IE11, in practice from the 3.0 release onward. 

If this causes an issue for anyone, now is the time to speak up. If you do want to argue for continued support, please bring good arguments and preferably budget :)

As per governance issue #3 our way forward regarding bootstrap release and further development:
- pre-bootstrap UI: 2.x: fixes for security issues and major bugs only
- bootstrap UI:  3.x: only branch with active feature development

**Below some background links on the issue:**

Microsoft itself announced that it'll no longer support IE11 for Office 365 as of August 2021. 
https://www.zdnet.com/article/microsoft-sets-deadline-for-end-of-support-of-ie-11-by-365-apps/

Many other major web services have already stopped supporting it (but note the URL of the source of this info)
https://death-to-ie11.com

Some considerations from a random software developer:
https://blog.logrocket.com/should-you-drop-support-for-internet-explorer-11/

**Comment by madsi1m** [comment]
How do we query the db/stats to see if anyone is using IE11?

**Comment by meijer** [comment]
Iirc this is not logged in the stats database, so you'd have to consult the webserver logs. Last time I did this (granted, that was many years ago) I could find a particular URL that typically denoted start of session, after which grep and awk turned that into a number. No access to a live filesender instance atm, so can't check this.

**Comment by monkeyiq** [comment]
The main stats page shows "Internet Explorer" for browsers with MSIE in their HTTP_USER_AGENT. We could maybe make a specific enum for IE11 as a browser type to allow collecting that. Though I don't imagine anyone would be using a different version of IE than 11 these days. If you have heaps of "Internet Explorer" on the stats page then we might have to add some narrowing down to log a count very specifically of just IE11 (and work out what the false positives are).

**Comment by madsi1m** [comment]
I'm on an old version:

select additional_attributes from StatLogs where additional_attributes like "%user_agent%" AND LOWER(additional_attributes) like "%internet%";

Shows no results. Seems our users are chrome and firefox

**Comment by monkeyiq** [comment]
Depending on what values you get for user_agent you might like to check for MSIE and WOW64 for matches.

You can run ie11 on windows 10 but you have to want to do it. So it is likely folks forced to use win7 for some reason who would be on ie11.  I am not to sure of what security you would get from ie11 as a main browser these days.

**Comment by WebSpider** [comment]
Has the decision been made to drop IE11 support in FS3.0?

**Comment by monkeyiq** [comment]
I do now know how well if at all the RNP version of the 3.x UI works in IE11. I think I will assume IE11 is too old and close this now. If folks are not using the non chromium based Edge these days IE11 is probably to old.
